alg_name: randsac
alpha_lr: 3e-4
delay_alpha_update: 250
diffusion_hidden_dim: 256
diffusion_steps: 20
hidden_dim: 1024
policy_hidden_dim: 256
hidden_num: 2
lr: 0.0003
repr_lr: 3e-4
lr_schedule_end: 3.0e-04
repr_dim: 2048
target_entropy_scale: 1.5
use_ema_policy: true
w_hidden_activation: 0
w_hidden_num: 0

# random mu related
random_feature_dim: 8192
sigma: 0.05

